/*
DROP TABLE IF EXISTS TREATMENT_PLAN;

CREATE TABLE TREATMENT_PLAN (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ACTION_TYPE INT NOT NULL,
    SUBJECT_PATIENT VARCHAR(100) NOT NULL,
    START_TIME TIMESTAMP NOT NULL,
    END_TIME TIMESTAMP,
    RECURRENCE_PATTERN VARCHAR(500) NOT NULL
);

DROP TABLE IF EXISTS TREATMENT_TASK;

CREATE TABLE TREATMENT_TASK (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ACTION_TYPE INT NOT NULL,
    SUBJECT_PATIENT VARCHAR(100) NOT NULL,
    START_TIME TIMESTAMP NOT NULL,
    STATUS INT NOT NULL DEFAULT 0,
    TREATMENT_PLAN_ID INT NOT NULL,
    CONSTRAINT TREAT_TASK_TREAT_PLAN_FK FOREIGN KEY (TREATMENT_PLAN_ID) REFERENCES TREATMENT_PLAN(ID)
);
*/